#+latex_class: article
#+latex_class_options:
#+latex_header: \usepackage{graphicx} \usepackage{svg} \usepackage{indentfirst} \usepackage[a4paper, margin=2.5cm]{geometry}
#+latex_header: \usepackage{tocbibind} \usepackage{tocloft} \setlength{\parindent}{2em} \usepackage{hyperref}
#+latex_header: \hypersetup{colorlinks=true, linkcolor=blue, filecolor=magenta, urlcolor=cyan} \urlstyle{same}
#+latex_header_extra:
#+latex_compiler: pdflatex
#+exclude_tags: noexport
#+options: ^:nil _:nil {}:t
#+startup: content
#+title: Python Script Reference Document
#+description: Learner's notes
#+keywords: notes, python, reference, document
#+subtitle: An elaboration of all the contents learned for Python Scripting.
#+date: \today
* Introduction
Python is a high-level, general-purpose programming language. It's design philosophy emphasizes code readability with the use of
significant indentation.

Python is dynamically typed and garbage-collected. It supports multiple programming paradigms, including structured
(particularly procedural), object-oriented and functional programming. It is often described as a "batteries included"
language due to its comprehensive standard library.

*Guido van Rossum* began working on Python in the late 1980s as a successor to the ABC programming language and first released it
in 1991 as Python 0.9.0. Python 2.0 was released in 2000. Python 3.0, released in 2008, was a major revision not completely
backward-compatible with earlier versions. Python 2.7.18, released in 2020, was the last release of Python 2.

Python consistently ranks as one of the most popular programming languages, and has gained widespread use in the machine
learning community.

** Philosophy

The core philosophy is summerized in the [[https://en.wikipedia.org/wiki/Zen_of_Python][Zen of Python]](PEP 20), which includes aphorisms such as,

+ Beautiful is better than ugly.
+ Explicit is better than implicit.
+ Simple is better than complex.
+ Complex is better than complicated.
+ Readability counts.

* References
1. [[https://pyflo.net/][PyFlo for learning sequencially]] (Tutorial website based on a learning flow-chart)
